Fix for k3s certificate expired error during the inital bootup on Raspberry pi
- this issue happens only during the intial bootup due to time sync
mismatch
ERROR: Unable to connect to the server: x509: certificate has expired or
is not yet valid